# Generated by Django 5.2.5 on 2025-08-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.DecimalField(decimal_places=2, help_text='Size in square meters', max_digits=7)),
                ('room', models.PositiveIntegerField(help_text='Number of rooms')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('number_of_adults', models.PositiveIntegerField()),
                ('number_of_children', models.PositiveIntegerField()),
                ('is_student', models.BooleanField(default=False)),
                ('university_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
