# Generated by Django 5.2.5 on 2025-08-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_user_tenancy_base_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenancy',
            old_name='room',
            new_name='total_rooms',
        ),
        migrations.AddField(
            model_name='tenancy',
            name='gym_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance to nearest gym (km)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='hospital_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance to nearest hospital (km)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='school_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance to nearest school (km)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='supermarket_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance to nearest supermarket (km)', max_digits=6, null=True),
        ),
    ]
