# Generated by Django 5.2.5 on 2025-08-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_distance_fields_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the property', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the property', max_digits=9, null=True),
        ),
    ]
